name: Build and Deploy Application 
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'releases/**'
      - 'release/**'
      - 'develop'
      - 'feature/**'
      - 'feat/**'
      - 'hotfix/**'
    paths-ignore:
      - 'docs/**'
jobs:
  build-and-push:
    uses: eduardo854/.github/.github/workflows/app-helm-release.yaml@test
    with:
      os_version: "ubuntu-latest"
      github_sha: ${{ github.sha }}
      github_repository: ${{ github.repository }}
      github_run_number: ${{ github.run_number }}
      github_ref_name: ${{ github.ref_name }}
      docker_context: "."
      docker_file_name: "./Dockerfile"
      helm_context: "helm"
      helm_url_repository: ${{ vars.url_helm_repository }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      TOKEN_HELM_STORE: ${{ secrets.TOKEN_HELM_STORE }}
